name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update environment
      run: |
          rustup default stable
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly
    
    - name: Build the docs
      run: cargo doc
   
    - name: Deploy the docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
