name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cargo doc
      run: cargo doc
    - name: Run tests
      run: cargo test --verbose
